### ISSUE TITLE
Removing month name abbreviation for certain months

### ISSUE THREAD

**Issue by witch-please** [witch-please/daily-moon#1]
The date displays abbreviated month names after the 3rd letter --> "Apr.", "Oct.", etc.
But for ex. "May" only contains 3 letters so the date is displayed as "May. 02, 2020".

Add a condition to display full month name (= not abbreviated with the dot) for the following months:
- May
- June
- July

**Comment by adrian3d** [comment]
That should be a short task.

We have to take it into account when we will implement the translation system in the future. So, Carbon support a localization feature that we won't be able to rely on.

**Comment by adrian3d** [comment]
A new release has been created: https://github.com/witch-please/daily-moon/releases/tag/v1.2
