### ISSUE TITLE
Add moon image options in plugin settings in WP back-office

### ISSUE THREAD

**Issue by witch-please** [witch-please/daily-moon#2]
**Option 1: select image type to display.**

The API allows to choose between 6 moon image "models".
Add an option that allows the user the choose the preferred image type directly inside WP back-office, in the plugin settings.

The image type is &model=1 in the API URL.

Option would ideally be a drop-down menu where user choose model, from "model 1" to "model 6".

By default the plugin is setup on Model 5.

---

**Option 2: select moon image's background color.**

In the same way, the API allows to choose the background color for the moon image: &bg=FFFFFF.

The option would be great to allow users choose their own background color when setting up the plugin in WP back-office.

Color is defined by entering HEX color code in WP plugin options.

By default the background color for the plugin is white.

--- 

**For the 2 OPTIONS:** no need to preview the image in WP plugin options, the user will see the changes (color and image type) directly on the website.

**Comment by adrian3d** [comment]
I think we split this feature into three parts:
- The first one will be dedicated to introducing a db connection into the codebase to store/read the plugin settings from the `wp_options` table. I'll probably add some integration tests to do it.
- The next ones would be bringing the two options into the admin.

This is a huge amount of work but once the db connection stuff has been tackled, that would be easy to introduce new options.
